# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec7591f46c04d10d368230612b282ee75b8469634ac26c9018965947074ceee96d7e2d1024558a8bb816c8899db74e39b2e8384aaba852fd7c3306d8d2344d17

test:
  secret_key_base: 0e24f6836f0084228cdea9ea6fa060cb2e2cdd189341a7cc9d60e3684e8a2b01b4da3e5fa90f78effd6f1647d27ee6b42adcb59b62d715f021d8a88fb744f182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
